spring.datasource.url=jdbc:postgresql://localhost:5432/inventory_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=public

app.jwt.secret=K8s9vPq2rX1bF6tY7mZ4nD3wQ2eR5tV6
app.jwt.expiration=86400000